Name: ambassador

global:
  imagePullPolicy: IfNotPresent

  rbac:
    enabled: true

  scheduling: &scheduling
    enabled: true

    rules:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - 'services'

backend:
  image:
    name: gcr.io/google_containers/defaultbackend
    tag: 1.4

  service:
    port: 80
    targetPort: 8080
    type: ClusterIP

  replicas: 1

  resources:
    limits:
      cpu: 10m
      memory: 20Mi
    requests:
      cpu: 10m
      memory: 20Mi

  scheduling:
    <<: *scheduling

controller:
  image:
    name: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
    tag: 0.12.0

  replicas: 1

  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
       # Enable PROXY protocol
      service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
       # Increase the ELB idle timeout to avoid issues with WebSockets or Server-Sent Events.
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '3600'
    ports:
    - port: 80
      name: http
      targetPort: 80
    - port: 443
      name: https
      targetPort: 443
