apiVersion: v1
kind: Service
metadata:
  labels:
    chart: {{ .Chart.Name }}
    component: {{ template "fullname" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    app: default-http-backend
  name: default-http-backend
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
spec:
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.targetPort }}
  type: {{ .Values.backend.service.type }}
  selector:
    app: default-http-backend
