apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    chart: {{ .Chart.Name }}
    component: {{ template "fullname" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
  name: ingress-nginx
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
